weibo_product/users/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__version__ = '1.0.0.0'
from django.conf.urls import url
from .views import LoginView, RegisterView,LogoutView


"""
@brief 简介 
@details 详细信息
@author  zhphuang
@data    2018-03-28 
"""

urlpatterns = [
    url(r'login/', LoginView.as_view(), name="login"),
    url(r'logout/', LogoutView.as_view(), name="logout"),
    url('register/', RegisterView.as_view(), name="register"),
]

weibo_product/weibo_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myapp.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name = 'index'),
    url(r'^keywords$', KeywordsView.as_view(), name = 'keywords'),
    url(r'^fans$', RMRBFansView.as_view(), name = 'fans'),
    url(r'^send$', SendCountView.as_view(), name = 'send'),
    url('^users/', include('users.urls', namespace = "users")),
]

weibo_product/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.hashers import make_password
# Create your models here.


class UserProfile(AbstractUser):
    mobile = models.CharField(max_length=11, null=True, blank=True)
    image = models.ImageField(upload_to="images/%Y/%m", default=u"images/default.jpg", max_length=100, blank = True)

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name

    def save(self, *args, **kwargs):
        if self.password.find("pbkdf2_sha256$") ==-1:
            self.password = make_password(self.password)
        return super(UserProfile, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.username






weibo_product/users/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms

__version__ = '1.0.0.0'

"""
@brief 简介 
@details 详细信息
@author  zhphuang
@data    2018-03-28 
"""


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码", "value": "", "required": "required"}),
                               min_length=5, max_length=20, error_messages={"required": "密码不能为空"})


class RegisterForm(forms.Form):
    username = forms.CharField(min_length = 3, max_length=20, error_messages={"required": "密码不能为空"})
    email = forms.EmailField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "请输入绑定邮箱账号", "value": ""}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码", "value": "", "required": "required"}),
                               min_length=5, max_length=20, error_messages={"required": "密码不能为空"})

weibo_product/users/views.py
import json
from django.shortcuts import render
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.views.generic.base import View
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import UserProfile
from .forms import LoginForm, RegisterForm
from django.contrib.auth.hashers import make_password
# Create your views here.


class CustomBackend(ModelBackend):
    def authenticate(self, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None


class LoginView(View):
    def get(self, request):
        return render(request, "users/login.html")

    def post(self, request):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user_name = request.POST.get("username", "")
            pass_word = request.POST.get("password", "")
            user = authenticate(username=user_name, password=pass_word)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return render(request, "users/login.html", {"msg":"用户名或密码错误！"})
        else:
            return render(request, "users/login.html", {"login_form": login_form})


class LogoutView(View):
    """
    用户登出
    """
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse("users:login"))


class RegisterView(View):

    def get(self, request):
        return render(request, "users/register.html")

    def post(self, request):
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user_name = request.POST.get("username", "")
            email = request.POST.get("email", "")
            if UserProfile.objects.filter(Q(username=user_name) | Q(email=email)):
                return HttpResponse(json.dumps({"status": -1, "msg": "用户已经存在"}), content_type = 'application/json')
            pass_word = request.POST.get("password", "")
            user_profile = UserProfile()
            user_profile.username = user_name
            user_profile.email = email
            user_profile.is_active = True
            user_profile.password = make_password(pass_word)
            user_profile.save()
            return render(request, "users/register.html", {"msg":"注册成功！<a href='/users/login' class='am-btn am-btn-default'>去登陆</a>"})
        else:
            msg = ""
            for key, error in register_form.errors.items():
                msg += "<p>%s</p>" % error
            return render(request, "users/register.html", {"msg": msg})

weibo_product/templates/users/login.html
{% load staticfiles %}
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="pragma" content="no-cache">
        <meta http-equiv="cache-control" content="no-cache">
        <meta http-equiv="expires" content="0">
        <title>登录界面</title>
        <link rel="stylesheet" href="/static/assets/css/amazeui.min.css" />
        <link rel="stylesheet" href="/static/assets/css/admin.css">
        <link rel="stylesheet" href="/static/assets/css/app.css">
        <style type="text/css">
            .error{
                background: #fb8344;
                color:#fff !important;
                text-align: center;
                line-height: 40px !important;
                margin:10px 0;}
        </style>
    </head>

    <body data-type="login">
        <div class="am-g myapp-login">
            <div class="myapp-login-logo-block  tpl-login-max">
                <div class="myapp-login-logo-text">
                    <div class="myapp-login-logo-text">微博数据分析系统<span> 登录</span> <i class="am-icon-skyatlas"></i>
                    </div>
                </div>
                <div class="am-u-sm-10 login-am-center">
                    <form class="am-form" method="post" action="{% url 'users:login' %}">
                        <fieldset>
                            <div class="am-form-group">
                                <input type="text" class="" name="username" id="doc-ipt-email-1" placeholder="输入用户名">
                            </div>
                            <div class="am-form-group">
                                <input type="password" name="password" class="" id="doc-ipt-pwd-1" placeholder="输入密码">
                            </div>
                            {% csrf_token %}
                            <p>
                                <button type="submit" class="am-btn am-btn-default">登录</button>

                            </p>
                            <p>
                                <a class="am-btn am-btn-default" href="{% url 'users:register'%}">去注册</a>
                            </p>
                        </fieldset>
                        <div class="error btns" id="jsEmailTips">{{ msg | safe }}</div>
                    </form>
                </div>
            </div>
        </div>
        <script src="/static/assets/js/jquery.min.js"></script>
        <script src="/static/assets/js/amazeui.min.js"></script>
        <script src="/static/assets/js/app.js"></script>
    </body>
</html>

weibo_product/templates/users/register.html
{% load staticfiles %}
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="pragma" content="no-cache">
        <meta http-equiv="cache-control" content="no-cache">
        <meta http-equiv="expires" content="0">
        <title>注册界面</title>
        <link rel="stylesheet" href="/static/assets/css/amazeui.min.css" />
        <link rel="stylesheet" href="/static/assets/css/admin.css">
        <link rel="stylesheet" href="/static/assets/css/app.css">
        <style type="text/css">
            .error{
                background: #fb8344;
                color:#fff !important;
                text-align: center;
                line-height: 40px !important;
                margin:10px 0;}
        </style>
    </head>

    <body data-type="login">
        <div class="am-g myapp-login">
            <div class="myapp-login-logo-block  tpl-login-max">
                <div class="myapp-login-logo-text">
                    <div class="myapp-login-logo-text">
                        微博数据分析系统<span> 注册</span> <i class="am-icon-skyatlas"></i>
                    </div>
                </div>
                <div class="am-u-sm-10 login-am-center">
                    <form class="am-form" method="post" action="{% url 'users:register' %}">
                        <fieldset>
                            <div class="am-form-group">
                                <input type="text" class="" name="username" id="doc-ipt-email-1" placeholder="输入用户名">
                            </div>
                            <div class="am-form-group">
                                <input type="email" name="email" class="" id="doc-ipt-email-1" placeholder="绑定邮箱">
                            </div>
                            <div class="am-form-group">
                                <input type="password" name="password" class="" id="doc-ipt-pwd-l" placeholder="输入密码">
                            </div>
                            {% csrf_token %}
                            <p><button type="submit" class="am-btn am-btn-default">注册</button></p>
                        </fieldset>
                        <div class="error btns" id="jsEmailTips">{{ msg | safe }}</div>

                    </form>
                </div>
            </div>
        </div>
        <script src="/static/assets/js/jquery.min.js"></script>
        <script src="/static/assets/js/amazeui.min.js"></script>
        <script src="/static/assets/js/app.js"></script>
    </body>
</html>