weibo_product/users/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__version__ = '1.0.0.0'
from django.conf.urls import url
from .views import LoginView, RegisterView,LogoutView


"""
@brief 简介 
@details 详细信息
@author  zhphuang
@data    2018-03-28 
"""

urlpatterns = [
    url(r'login/', LoginView.as_view(), name="login"),
    url(r'logout/', LogoutView.as_view(), name="logout"),
    url('register/', RegisterView.as_view(), name="register"),
]

weibo_product/weibo_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myapp.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name = 'index'),
    url(r'^keywords$', KeywordsView.as_view(), name = 'keywords'),
    url(r'^fans$', RMRBFansView.as_view(), name = 'fans'),
    url(r'^send$', SendCountView.as_view(), name = 'send'),
    url('^users/', include('users.urls', namespace = "users")),
]

weibo_product/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>微博数据数据web分析平台</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta name="description" content="Developed By M Abdur Rokib Promy">
    <meta name="keywords" content="Admin, Bootstrap 3, Template, Theme, Responsive">
    <!-- bootstrap 3.0.2 -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/ionicons.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/morris/morris.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/jvectormap/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/datepicker/datepicker3.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/daterangepicker/daterangepicker-bs3.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/iCheck/all.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <script src="{% static 'js/echarts.min.js' %}"></script>
    <script type="text/javascript" src="http://libs.baidu.com/jquery/2.1.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery.cookie.js' %}" type="text/javascript"></script>

    {% block customstyle %}{% endblock %}
    <style type="text/css">
    </style>
    </head>
    <body class="skin-black">
    <header class="header">
        <a href="{% url 'index' %}" class="logo">
            WeiboDataWeb
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="navbar-right">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-user"></i>
                            <span>{{ request.user }}<i class="caret"></i></span>
                        </a>
                        <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
                            <li class="dropdown-header text-center"><a href="{% url 'users:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="wrapper row-offcanvas row-offcanvas-left">
        <aside class="left-side sidebar-offcanvas" style="height: 1200px;">
            <section class="sidebar">
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="{% static 'img/26115.jpg' %}" class="img-circle" alt="User Image" />
                    </div>
                    <div class="pull-left info">
                        <p>Hello, {{ request.user }}</p>
                        <a href="#"><i class="fa fa-circle text-success"></i>Online</a>
                    </div>
                </div>
                <!-- search form -->
                <form action="{% url 'index' %}" method="post" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search..."/>
                        <span class="input-group-btn">
                            <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                    {% csrf_token %}
                </form>
                <ul class="sidebar-menu">
                    <li {% if request.path == '/' %} class="active" {% endif %}>
                        <a href="{% url 'index' %}">
                            <i class="fa fa-columns"></i><span>人民日报总览</span>
                        </a>
                    </li>

                    <li {% if request.path == '/keywords/' %} class="active" {% endif %}>
                        <a href="{% url 'keywords' %}">
                            <i class="fa fa-columns"></i> <span>关键字信息</span>
                        </a>
                    </li>
                    <li {% if request.path == '/fans/' %} class="active" {% endif %}>
                        <a href="{% url 'fans' %}">
                            <i class="fa fa-dashboard"></i> <span>粉丝信息</span>
                        </a>
                    </li>
                    <li {% if request.path == '/send/' %} class="active" {% endif %}>
                        <a href="{% url 'send' %}">
                            <i class="fa fa-briefcase"></i> <span>转发量总览</span>
                        </a>
                    </li>
                </ul>
            </section>
        </aside>
        <div class="copyrights">niuniuc<a href="#" >微博数据web分析平台</a></div>
        <aside class="right-side">
            <section class="content">
                {% block content %}{% endblock %}
            </section>
            <div class="footer-main">
                Copyright &copy niuniuc, 2018 <a href="#" target="_blank">微博数据web分析平台</a>
            </div>
        </aside>
    </div>
    </body>
    {% block customjs %}{% endblock %}
</html>

weibo_product/templates/fans.html
{% extends 'base.html' %}
{% block customstyle %}
     <script src="http://gallery.echartsjs.com/dep/echarts/map/js/world.js"></script>
{% endblock %}
{% load staticfiles %}
{% block content %}
    <div class="row" style="border: solid 1px #39445c;">
        <div id="main" style="width: 60%;height:400px; margin: auto;"></div>
        <script type="text/javascript">
            var myChart = echarts.init(document.getElementById('main'));
            myChart.setOption({
                title: {
                    text: '人民日报粉丝男女比例'
                },
                tooltip: {
                    trigger: 'axis',
                    formatter: "{a} <br/>{b} : {c} ({d}%)"
                },
                legend: {
                    bottom: 10,
                    left: 'center',
                    data: ['男', '女']
                },
                series: [{
                    type: 'pie',
                    name: '男女比例',
                    radius : '65%',
                    center: ['50%', '50%'],
                    selectedMode: 'single',
                    data: []
                }]
            });
            myChart.showLoading();
            $.post("{% url 'fans' %}", {"type": 1}, function(result){
                 myChart.hideLoading();    //隐藏加载动画
                 myChart.setOption({        //加载数据图表
                                series: [{
                                    // 根据名字对应到相应的系列
                                    name: '男女比例',
                                    data: result.persent
                                }]
                            });
            });
        </script>
    </div>
    <div class="row" style="border: solid 1px #39445c;">
        <div id="main2" style="width: 100%;height:400px; margin: auto;"></div>
        <script type="text/javascript">
            var myChart2 = echarts.init(document.getElementById('main2'));
            myChart2.setOption({
                title: {
                    text: '人民日报粉丝地区柱状图'
                },
                tooltip: {
                    trigger: 'axis',
                    axisPointer: {
                        type: 'shadow'
                    }
                },
                legend: {
                    data:['数量']
                },

                yAxis: {
                    type: 'value',
                },
                xAxis: {
                    type: 'category',
                    data: []
                },
                series: [{
                    name: '数量',
                    type: 'bar',
                    data: []
                }]
            });
            myChart2.showLoading();
            $.post("{% url 'fans' %}", {"type": 2}, function(result){
                 myChart2.hideLoading();    //隐藏加载动画
                 myChart2.setOption({        //加载数据图表
                                xAxis: {
                                    data: result.location
                                },
                                series: [{
                                    // 根据名字对应到相应的系列
                                    name: '数量',
                                    data: result.count
                                }]
                            });
            });
        </script>
    </div>
{% endblock %}

{% block customjs %}
    <script>

    </script>

{% endblock %}



weibo_product/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block customstyle %}
    <script type="text/javascript" src="http://libs.baidu.com/jquery/2.1.1/jquery.min.js"></script>
    <script language="JavaScript" type="text/javascript" src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js" charset="utf-8"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <style type="text/css">
        body{overflow-x:hidden; background:#f2f0f5;}
        #main-tab {
            border: 1px solid #eaeaea;
            background: #FFF;
            font-size: 12px;
            margin: auto;
        }
        tbody {
            display: table-row-group;
            vertical-align: middle;
            border-color: inherit;
        }
        tr {
            display: table-row;
            vertical-align: inherit;
            border-color: inherit;
        }
        #main-tab td {
            font-size: 14px;
            line-height: 30px;
        }
        .borderright{ border-right:1px solid #ebebeb}
        .borderbottom{ border-bottom:1px solid #ebebeb}
        table {
            border-collapse:collapse;
            border-spacing:0;
            font-size:14px;
        }
        caption,th {
            text-align:left;
        }
        td.fenye{ padding:10px 0 0 0; text-align:right;}
        td.desp{
              width: 600px;
              line-height: 25px;
              align-content: left;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="row" style="margin-bottom:5px;">
        <div>
            <table width="80%" border="0" cellspacing="0" cellpadding="0" id="main-tab">
                <th>
                    <tr style="background-color: #39445c;color: white;">
                        <td align="center" valign="middle" class="borderright borderbottom">标题</td>
                        <td align="center" valign="middle" class="borderright borderbottom">内容</td>
                        <td align="center" valign="middle" class="borderright borderbottom">转发量</td>
                    </tr>
                </th>

                {% for item in paginator.object_list %}
                <tr onMouseOut="this.style.backgroundColor='#ffffff'" onMouseOver="this.style.backgroundColor='#edf5ff'">
                    <td align="center" valign="middle" class="borderright borderbottom">{{ item.title }}</td>
                    <td align="center" valign="middle" class="borderright borderbottom desp">{{ item.content }}</td>
                    <td align="center" valign="middle" class="borderright borderbottom">{{ item.send_count}}</td>

                </tr>
                {% endfor %}

            </table>
        </div>
        <div style="width: 80%;margin: auto">
             <ul class="pagination pagination-lg">
                {% if paginator.has_previous %}
                    <li>
                        <a href="{% url 'index' %}?page={{ paginator.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">上一页</span>
                        </a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <a href="#" aria-label="Previous">
                            <span aria-hidden="true">上一页</span>
                        </a>
                    </li>
                {% endif %}

                {% for number in paginator.paginator.pager_num_range %}
                    {% if number == paginator.number %}
                        <li class="active"><a href="{% url 'index' %}?page={{ number }}">{{ number }}</a></li>
                    {% else %}
                        <li><a href="{% url 'index' %}?page={{ number }}" >{{ number }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if paginator.has_next %}
                    <li>
                        <a href="{% url 'index' %}?page={{ paginator.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">下一页</span>
                        </a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <a href="#" aria-label="Next">
                            <span aria-hidden="true">下一页</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}



weibo_product/templates/keywords.html
{% extends 'base.html' %}
{% block customstyle %}
     <script src="http://gallery.echartsjs.com/dep/echarts/map/js/world.js"></script>
{% endblock %}
{% load staticfiles %}
{% block content %}
    <div class="row" style="border: solid 1px #39445c;">
        <div id="main" style="width: 45%;height:400px;float: left; margin-right: 5%"></div>
        <script type="text/javascript">
            var myChart = echarts.init(document.getElementById('main'));
            myChart.setOption({
                title: {
                    text: '人民日报关键字'
                },
                tooltip: {
                    trigger: 'axis',
                    axisPointer: {
                        type: 'shadow'
                    }
                },
                legend: {
                    data:['数量']
                },

                yAxis: {
                    type: 'value',
                },
                xAxis: {
                    type: 'category',
                    data: []
                },
                series: [{
                    name: '数量',
                    type: 'bar',
                    data: []
                }]
            });
            myChart.showLoading();
            $.post("{% url 'index' %}", {"type": 1}, function(result){
                 myChart.hideLoading();    //隐藏加载动画
                 myChart.setOption({        //加载数据图表
                                xAxis: {
                                    data: result.keyword
                                },
                                series: [{
                                    // 根据名字对应到相应的系列
                                    name: '数量',
                                    data: result.weight_count
                                }]
                            });
            });
        </script>
        <div id="main2" style="width: 45%;height:400px;float: left; margin-right: 5%"></div>
        <script type="text/javascript">
            var myChart2 = echarts.init(document.getElementById('main2'));
            myChart2.setOption({
                title: {
                    text: '中国青年报关键字'
                },
                tooltip: {
                    trigger: 'axis',
                    axisPointer: {
                        type: 'shadow'
                    }
                },
                legend: {
                    data:['数量']
                },

                yAxis: {
                    type: 'value',
                },
                xAxis: {
                    type: 'category',
                    data: []
                },
                series: [{
                    name: '数量',
                    type: 'bar',
                    data: []
                }]
            });
            myChart2.showLoading();
            $.post("{% url 'index' %}", {"type": 2}, function(result){
                 myChart2.hideLoading();    //隐藏加载动画
                 myChart2.setOption({        //加载数据图表
                                xAxis: {
                                    data: result.keyword
                                },
                                series: [{
                                    // 根据名字对应到相应的系列
                                    name: '数量',
                                    data: result.weight_count
                                }]
                            });
            });
        </script>
    </div>

    <div class="row" style="border: solid 1px #39445c;">
        <div id="main3" style="width: 45%;height:400px;float: left; margin-right: 5%"></div>
        <script type="text/javascript">
            var myChart3 = echarts.init(document.getElementById('main3'));
            myChart3.setOption({
                title: {
                    text: '新闻周刊关键字'
                },
                tooltip: {
                    trigger: 'axis',
                    axisPointer: {
                        type: 'shadow'
                    }
                },
                legend: {
                    data:['数量']
                },

                yAxis: {
                    type: 'value',
                },
                xAxis: {
                    type: 'category',
                    data: []
                },
                series: [{
                    name: '数量',
                    type: 'bar',
                    data: []
                }]
            });
            myChart3.showLoading();
            $.post("{% url 'index' %}", {"type": 3}, function(result){
                 myChart3.hideLoading();    //隐藏加载动画
                 myChart3.setOption({        //加载数据图表
                                xAxis: {
                                    data: result.keyword
                                },
                                series: [{
                                    // 根据名字对应到相应的系列
                                    name: '数量',
                                    data: result.weight_count
                                }]
                            });
            });
        </script>
        <div id="main4" style="width: 45%;height:400px;float: left; margin-right: 5%"></div>
        <script type="text/javascript">
            var myChart4 = echarts.init(document.getElementById('main4'));
            myChart4.setOption({
                title: {
                    text: '头条新闻关键字'
                },
                tooltip: {
                    trigger: 'axis',
                    axisPointer: {
                        type: 'shadow'
                    }
                },
                legend: {
                    data:['数量']
                },

                yAxis: {
                    type: 'value',
                },
                xAxis: {
                    type: 'category',
                    data: []
                },
                series: [{
                    name: '数量',
                    type: 'bar',
                    data: []
                }]
            });
            myChart4.showLoading();
            $.post("{% url 'index' %}", {"type": 4}, function(result){
                 myChart4.hideLoading();    //隐藏加载动画
                 myChart4.setOption({        //加载数据图表
                                xAxis: {
                                    data: result.keyword
                                },
                                series: [{
                                    // 根据名字对应到相应的系列
                                    name: '数量',
                                    data: result.weight_count
                                }]
                            });
            });
        </script>
    </div>
{% endblock %}

{% block customjs %}
    <script>

    </script>

{% endblock %}



weibo_product/templates/sended.html
{% extends 'base.html' %}
{% block customstyle %}
     <script src="http://gallery.echartsjs.com/dep/echarts/map/js/world.js"></script>
{% endblock %}
{% load staticfiles %}
{% block content %}
    <div class="row" style="border: solid 1px #39445c;">
        <div id="main" style="width: 80%;height:500px; margin: auto;"></div>
        <script type="text/javascript">
            var myChart = echarts.init(document.getElementById('main'));
            myChart.setOption({
                title: {
                    text: '微博转发量比例'
                },
                tooltip: {
                    trigger: 'axis',
                    formatter: "{a} <br/>{b} : {c} ({d}%)"
                },
                legend: {
                    bottom: 10,
                    left: 'center',
                    data: ['人民日报', '中国青年报', '新闻周刊', '头条新闻']
                },
                series: [{
                    type: 'pie',
                    name: '微博转发比例',
                    radius : '65%',
                    center: ['50%', '50%'],
                    selectedMode: 'single',
                    data: []
                }]
            });
            myChart.showLoading();
            $.post("{% url 'send' %}", {"type": 1}, function(result){
                 myChart.hideLoading();    //隐藏加载动画
                 myChart.setOption({        //加载数据图表
                                series: [{
                                    // 根据名字对应到相应的系列
                                    name: '微博转发比例',
                                    data: result.persent
                                }]
                            });
            });
        </script>
    </div>

{% endblock %}

{% block customjs %}
    <script>

    </script>

{% endblock %}

